# These are the legislative members and their associated districts
SENATORS = {
    'Brian Dahle': 'SD 01',
    'Mike McGuire': 'SD 02',
    'Bill Dodd': 'SD 03',
    'Marie Alvarado-Gil': 'SD 04',
    'Susan Talamantes Eggman': 'SD 05',
    'Roger Niello': 'SD 06',
    'Steven Glazer': 'SD 07',
    'Angelique Ashby': 'SD 08',
    'Nancy Skinner': 'SD 09',
    'Aisha Wahab': 'SD 10',
    'Scott Wiener': 'SD 11',
    'Shannon Grove': 'SD 12',
    'Josh Becker': 'SD 13',
    'Anna Caballero': 'SD 14',
    'Dave Cortese ': 'SD 15',
    'Melissa Hurtado': 'SD 16',
    'John Laird': 'SD 17',
    'Steve Padilla': 'SD 18',
    'Monique Limon': 'SD 19',
    'Caroline Menjivar': 'SD 20',
    'Scott Wilk': 'SD 21',
    'Susan Rubio': 'SD 22',
    'Rosilicie Ochoa Bogh': 'SD 23',
    'Ben Allen': 'SD 24',
    'Anthony Portantino': 'SD 25',
    'Maria Elena Durazo': 'SD 26',
    'Henry Stern': 'SD 27',
    'Lola Smallwood-Cuevas': 'SD 28',
    'Josh Newman': 'SD 29',
    'Bob Archuleta': 'SD 30',
    'Richard Roth': 'SD 31',
    'Kelly Seyarto': 'SD 32',
    'Lena Gonzalez': 'SD 33',
    'Thomas Umberg': 'SD 34',
    'Steven Bradford': 'SD 35',
    'Janet Nguyen': 'SD 36',
    'David Min': 'SD 37',
    'Catherine Blakespear': 'SD 38',
    'Toni Atkins': 'SD 39',
    'Brian Jones': 'SD 40'
}

ASM = {
    'Megan Dahle': 'AD 01',
    'Jim Wood': 'AD 02',
    'James Gallagher': 'AD 03',
    'Cecilia Aguiar-Curry': 'AD 04',
    'Joe Patterson': 'AD 05',
    'Kevin McCarthy': 'AD 06',
    'Josh Hoover': 'AD 07',
    'Jim Patterson': 'AD 08',
    'Heath Flora': 'AD 09',
    'Nguyen, Stephanie': 'AD 10',
    'Lori Wilson': 'AD 11',
    'Damon Connolly': 'AD 12',
    'Carlos Villapudua': 'AD 13',
    'Buffy Wicks': 'AD 14',
    'Timothy Grayson': 'AD 15',
    'Rebecca Bauer-Kahan': 'AD 16',
    'Matt Haney': 'AD 17',
    'Mia Bonta': 'AD 18',
    'Philip Ting': 'AD 19',
    'Ortega, Liz': 'AD 20',
    'Papan, Diane': 'AD 21',
    'Juan Alanis': 'AD 22',
    'Marc Berman': 'AD 23',
    'Alex Lee': 'AD 24',
    'Ash Kalra': 'AD 25',
    'Evan Low': 'AD 26',
    'Esmeralda Soria': 'AD 27',
    'Gail Pellerin': 'AD 28',
    'Robert Rivas': 'AD 29',
    'Dawn Addis': 'AD 30',
    'Joaquin Arambula': 'AD 31',
    'Vince Fong': 'AD 32',
    'Devon Mathis': 'AD 33',
    'Tom Lackey': 'AD 34',
    'Jasmeet Bains': 'AD 35',
    'Eduardo Garcia': 'AD 36',
    'Gregg Hart': 'AD 37',
    'Steve Bennett': 'AD 38',
    'Juan Carrillo': 'AD 39',
    'Pilar Schiavo': 'AD 40',
    'Chris Holden': 'AD 41',
    'Jacqui Irwin': 'AD 42',
    'Luz Rivas': 'AD 43',
    'Laura Friedman': 'AD 44',
    'James Ramos': 'AD 45',
    'Jesse Gabriel': 'AD 46',
    'Greg Wallis': 'AD 47',
    'Blanca Rubio': 'AD 48',
    'Mike Fong': 'AD 49',
    'Eloise Gomez Reyes': 'AD 50',
    'Rick Chavez Zbur': 'AD 51',
    'Wendy Carrillo': 'AD 52',
    'Freddie Rodriguez': 'AD 53',
    'Miguel Santiago': 'AD 54',
    'Isaac Bryan': 'AD 55',
    'Lisa Calderon': 'AD 56',
    'Reginald Byron Jones-Sawyer': 'AD 57',
    'Sabrina Cervantes': 'AD 58',
    'Phillip Chen': 'AD 59',
    'Corey Jackson': 'AD 60',
    'Tina McKinnor': 'AD 61',
    'Anthony Rendon': 'AD 62',
    'Bill Essayli': 'AD 63',
    'Pacheco, Blanca': 'AD 64',
    'Mike Gipson': 'AD 65',
    'Al Muratsuchi': 'AD 66',
    'Sharon Quirk-Silva': 'AD 67',
    'Avelino Valencia': 'AD 68',
    'Josh Lowenthal': 'AD 69',
    'Tri Ta': 'AD 70',
    'Kate Sanchez': 'AD 71',
    'Diane Dixon': 'AD 72',
    'Cottie Petrie-Norris': 'AD 73',
    'Laurie Davies': 'AD 74',
    'Marie Waldron': 'AD 75',
    'Brian Maienschein': 'AD 76',
    'Tasha Boerner': 'AD 77',
    'Christopher Ward': 'AD 78',
    'Akilah Weber': 'AD 79',
    'David Alvarez': 'AD 80'
}

# to sort by value in dict
#new_senators = {k: v for k, v in sorted(SENATORS.items(), key=lambda item: item[1])}