quarterly_performance_report:
	#cd ../bus_service_increase/ && make setup_bus_service_utils && cd ..
	python A1_scheduled_route_level_df.py
	python A2_generate_routes_on_shn_data.py
	python A3_categorize_routes.py
	python A4_add_route_speeds.py
    