quarterly_performance_report:
	#cd ../bus_service_increase/ && make setup_bus_service_utils && cd ..
	#cd ../rt_delay/ && make setup_rt_analysis && cd ../quarterly_performance_metrics/
	python A1_scheduled_route_level_df.py
	python A2_generate_routes_on_shn_data.py
	python A3_categorize_routes.py
	#python B1_generate_endpoint_delay.py
	#python B2_route_service_hours_delay.py
    