dla:
  notebook: ./dla/e76_obligated_funds/prototype-district.ipynb
  params:
    district:
      - 4
      - 7
dla_interactive:
  notebook: ./dla/e76_obligated_funds/interactive_functions_1.ipynb
  prepare_only: yes