from shared_utils.models.base import get_table_name
from sqlalchemy import Boolean, Column, Date, DateTime, Float, Integer, String
from sqlalchemy.orm import declarative_base, declared_attr

Base = declarative_base()


class FctScheduledTrip(Base):
    dataset = "mart_gtfs"
    table = "fct_scheduled_trips"

    @declared_attr
    def __tablename__(cls):
        return get_table_name(cls.dataset, cls.table)

    key = Column(String, primary_key=True)
    trip_instance_key = Column(String)
    feed_timezone = Column(String)
    base64_url = Column(String)
    name = Column(String)
    regional_feed_type = Column(String)
    gtfs_dataset_key = Column(String)
    service_date = Column(Date)
    feed_key = Column(String)
    service_id = Column(String)
    trip_key = Column(String)
    trip_id = Column(String)
    iteration_num = Column(Integer)
    frequencies_defined_trip = Column(Boolean)
    trip_short_name = Column(String)
    direction_id = Column(Integer)
    block_id = Column(String)
    route_key = Column(String)
    route_id = Column(String)
    route_type = Column(String)
    route_short_name = Column(String)
    route_long_name = Column(String)
    route_continuous_pickup = Column(Integer)
    route_continuous_drop_off = Column(Integer)
    route_desc = Column(String)
    route_color = Column(String)
    route_text_color = Column(String)
    agency_id = Column(String)
    network_id = Column(String)
    shape_array_key = Column(String)
    shape_id = Column(String)
    contains_warning_duplicate_trip_primary_key = Column(Boolean)
    num_distinct_stops_served = Column(Integer)
    num_stop_times = Column(Integer)
    trip_first_departure_sec = Column(Integer)
    trip_last_arrival_sec = Column(Integer)
    trip_start_timezone = Column(String)
    trip_end_timezone = Column(String)
    service_hours = Column(Float)
    flex_service_hours = Column(Float)
    contains_warning_duplicate_stop_times_primary_key = Column(Boolean)
    contains_warning_missing_foreign_key_stop_id = Column(Boolean)
    trip_first_departure_ts = Column(DateTime)
    trip_last_arrival_ts = Column(DateTime)
    first_start_pickup_drop_off_window_sec = Column(Integer)
    last_end_pickup_drop_off_window_sec = Column(Integer)
    is_gtfs_flex_trip = Column(Boolean)
    is_entirely_demand_responsive_trip = Column(Boolean)
    num_gtfs_flex_stop_times = Column(Integer)
    num_approximate_timepoint_stop_times = Column(Integer)
    num_exact_timepoint_stop_times = Column(Integer)
    num_arrival_times_populated_stop_times = Column(Integer)
    num_departure_times_populated_stop_times = Column(Integer)
    trip_first_start_pickup_drop_off_window_ts = Column(DateTime)
    trip_last_end_pickup_drop_off_window_ts = Column(DateTime)
    trip_start_date_pacific = Column(Date)
    trip_first_departure_datetime_pacific = Column(DateTime)
    trip_last_arrival_datetime_pacific = Column(DateTime)
    trip_start_date_local_tz = Column(Date)
    trip_first_departure_datetime_local_tz = Column(DateTime)
    trip_last_arrival_datetime_local_tz = Column(DateTime)
    trip_first_start_pickup_drop_off_window_date_pacific = Column(Date)
    trip_first_start_pickup_drop_off_window_datetime_pacific = Column(DateTime)
    trip_last_end_pickup_drop_off_window_pacific = Column(DateTime)
    trip_first_start_pickup_drop_off_window_date_local_tz = Column(Date)
    trip_first_start_pickup_drop_off_window_datetime_local_tz = Column(DateTime)
    trip_last_end_pickup_drop_off_window_datetime_local_tz = Column(DateTime)
    time_of_day = Column(String)
