# Remap names
combined_names_dict = {
    "Amtrak": "Amtrak Schedule",
    "San Joaquin Joint Powers Authority": "Amtrak Schedule",
    "Commute.org": "Commute.org and Menlo Park Community Shuttles Schedule",
    "City of Menlo Park": "Commute.org and Menlo Park Community Shuttles Schedule",
    "San Francisco Bay Area Water Emergency Transit Authority": "San Francisco Bay Ferry and Oakland Alameda Water Shuttle Schedule",
    "City of Alameda": "San Francisco Bay Ferry and Oakland Alameda Water Shuttle Schedule",
    "Solano County Transit": "SolTrans Schedule",
    "Solano Transportation Authority": "SolTrans Schedule",
    "Sonoma County": "Sonoma County Transit Schedule",
    "Cloverdale Transit": "Sonoma County Transit Schedule",
    "FlixBus": "FlixBus and Greyhound Schedule",
    "Greyhound": "FlixBus and Greyhound Schedule",
    "Foothill Transit": "Foothill Schedule",
    "City of Duarte": "Foothill Schedule",
    "Humboldt Transit Authority": "Humboldt Schedule",
    "City of Arcata": "Humboldt Schedule",
    "City of Eureka": "Humboldt Schedule",
    "Redding Area Bus Authority": "Redding Schedule",
    "Shasta County": "Redding Schedule",
    "Sacramento Regional Transit District": "Sacramento Schedule",
    "City of Rancho Cordova": "Sacramento Schedule",
    "San Diego Metropolitan Transit System": "San Diego Schedule",
    "Flagship Cruises and Events Inc.": "San Diego Schedule",
    "San Diego International Airport": "San Diego Schedule",
    "Tahoe Truckee Area Regional Transportation": "TART, North Lake Tahoe Schedule",
    "North Lake Tahoe Express": "TART, North Lake Tahoe Schedule",
    "Tehama County": "Tehama Schedule",
    "Susanville Indian Rancheria": "Tehama Schedule",
    "University of California, Santa Cruz": "UCSC and City of Santa Cruz Beach Shuttle Schedule",
    "City of Santa Cruz": "UCSC and City of Santa Cruz Beach Shuttle Schedule",
    "Ventura County Transportation Commission": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "City of Camarillo": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "City of Moorpark": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "City of Ojai": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "City of Simi Valley": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "City of Thousand Oaks": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
    "Gold Coast Transit District": "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule",
}