# Tagging if the number of unique routes have remained in the same over the last 3 months

'False':
  Butte County Association of Governments:
  - '2_months_ago: 20.0 routes'
  - '1_months_ago: 21.0 routes'
  - 'current_month: 20.0 routes'
  City and County of San Francisco:
  - '2_months_ago: 70.0 routes'
  - '1_months_ago: 70.0 routes'
  - 'current_month: 1.0 routes'
  City of Culver City:
  - '2_months_ago: 0.0 routes'
  - '1_months_ago: 11.0 routes'
  - 'current_month: 11.0 routes'
  City of Elk Grove:
  - '2_months_ago: 0.0 routes'
  - '1_months_ago: 0.0 routes'
  - 'current_month: 17.0 routes'
  City of Pasadena:
  - '2_months_ago: 6.0 routes'
  - '1_months_ago: 11.0 routes'
  - 'current_month: 11.0 routes'
  Emeryville Transportation Management Agency:
  - '2_months_ago: 1.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  Foothill Schedule:
  - '2_months_ago: 35.0 routes'
  - '1_months_ago: 35.0 routes'
  - 'current_month: 0.0 routes'
  Madera County:
  - '2_months_ago: 4.0 routes'
  - '1_months_ago: 4.0 routes'
  - 'current_month: 0.0 routes'
  Monterey-Salinas Transit:
  - '2_months_ago: 35.0 routes'
  - '1_months_ago: 36.0 routes'
  - 'current_month: 37.0 routes'
  Napa Valley Transportation Authority:
  - '2_months_ago: 11.0 routes'
  - '1_months_ago: 12.0 routes'
  - 'current_month: 12.0 routes'
  Orange County Transportation Authority:
  - '2_months_ago: 58.0 routes'
  - '1_months_ago: 56.0 routes'
  - 'current_month: 56.0 routes'
  Palo Verde Valley Transit Agency:
  - '2_months_ago: 10.0 routes'
  - '1_months_ago: 10.0 routes'
  - 'current_month: 9.0 routes'
  San Diego Schedule:
  - '2_months_ago: 100.0 routes'
  - '1_months_ago: 101.0 routes'
  - 'current_month: 101.0 routes'
  Santa Barbara Metropolitan Transit District:
  - '2_months_ago: 35.0 routes'
  - '1_months_ago: 36.0 routes'
  - 'current_month: 36.0 routes'
  SolTrans Schedule:
  - '2_months_ago: 17.0 routes'
  - '1_months_ago: 15.0 routes'
  - 'current_month: 17.0 routes'
  Tulare County Regional Transit Agency:
  - '2_months_ago: 25.0 routes'
  - '1_months_ago: 24.0 routes'
  - 'current_month: 24.0 routes'
  Tuolumne County Transit Agency:
  - '2_months_ago: 3.0 routes'
  - '1_months_ago: 3.0 routes'
  - 'current_month: 4.0 routes'
  University of California, Los Angeles:
  - '2_months_ago: 0.0 routes'
  - '1_months_ago: 4.0 routes'
  - 'current_month: 4.0 routes'
  Yolo County Transportation District:
  - '2_months_ago: 17.0 routes'
  - '1_months_ago: 17.0 routes'
  - 'current_month: 15.0 routes'
'True':
  Alameda-Contra Costa Transit District:
  - '2_months_ago: 130.0 routes'
  - '1_months_ago: 130.0 routes'
  - 'current_month: 130.0 routes'
  Anaheim Transportation Network:
  - '2_months_ago: 18.0 routes'
  - '1_months_ago: 18.0 routes'
  - 'current_month: 18.0 routes'
  Antelope Valley Transit Authority:
  - '2_months_ago: 20.0 routes'
  - '1_months_ago: 20.0 routes'
  - 'current_month: 20.0 routes'
  Basin Transit:
  - '2_months_ago: 14.0 routes'
  - '1_months_ago: 14.0 routes'
  - 'current_month: 14.0 routes'
  Capitol Corridor Joint Powers Authority:
  - '2_months_ago: 3.0 routes'
  - '1_months_ago: 3.0 routes'
  - 'current_month: 3.0 routes'
  Central Contra Costa Transit Authority:
  - '2_months_ago: 42.0 routes'
  - '1_months_ago: 42.0 routes'
  - 'current_month: 42.0 routes'
  City of Arcadia:
  - '2_months_ago: 3.0 routes'
  - '1_months_ago: 3.0 routes'
  - 'current_month: 3.0 routes'
  City of Banning:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  City of Beaumont:
  - '2_months_ago: 8.0 routes'
  - '1_months_ago: 8.0 routes'
  - 'current_month: 8.0 routes'
  City of Burbank:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  City of Cerritos:
  - '2_months_ago: 8.0 routes'
  - '1_months_ago: 8.0 routes'
  - 'current_month: 8.0 routes'
  City of Commerce:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  City of Escalon:
  - '2_months_ago: 1.0 routes'
  - '1_months_ago: 1.0 routes'
  - 'current_month: 1.0 routes'
  City of Fairfield:
  - '2_months_ago: 5.0 routes'
  - '1_months_ago: 5.0 routes'
  - 'current_month: 5.0 routes'
  City of Fresno:
  - '2_months_ago: 18.0 routes'
  - '1_months_ago: 18.0 routes'
  - 'current_month: 18.0 routes'
  City of Gardena:
  - '2_months_ago: 6.0 routes'
  - '1_months_ago: 6.0 routes'
  - 'current_month: 6.0 routes'
  City of Irvine:
  - '2_months_ago: 1.0 routes'
  - '1_months_ago: 1.0 routes'
  - 'current_month: 1.0 routes'
  City of Lawndale:
  - '2_months_ago: 4.0 routes'
  - '1_months_ago: 4.0 routes'
  - 'current_month: 4.0 routes'
  City of Los Angeles:
  - '2_months_ago: 64.0 routes'
  - '1_months_ago: 64.0 routes'
  - 'current_month: 64.0 routes'
  City of Montebello:
  - '2_months_ago: 8.0 routes'
  - '1_months_ago: 8.0 routes'
  - 'current_month: 8.0 routes'
  City of Monterey Park:
  - '2_months_ago: 5.0 routes'
  - '1_months_ago: 5.0 routes'
  - 'current_month: 5.0 routes'
  City of Norwalk:
  - '2_months_ago: 6.0 routes'
  - '1_months_ago: 6.0 routes'
  - 'current_month: 6.0 routes'
  City of Petaluma:
  - '2_months_ago: 10.0 routes'
  - '1_months_ago: 10.0 routes'
  - 'current_month: 10.0 routes'
  City of Redondo Beach:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  City of Rosemead:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  City of Santa Clarita:
  - '2_months_ago: 38.0 routes'
  - '1_months_ago: 38.0 routes'
  - 'current_month: 38.0 routes'
  City of Santa Maria:
  - '2_months_ago: 16.0 routes'
  - '1_months_ago: 16.0 routes'
  - 'current_month: 16.0 routes'
  City of Santa Monica:
  - '2_months_ago: 19.0 routes'
  - '1_months_ago: 19.0 routes'
  - 'current_month: 19.0 routes'
  City of Santa Rosa:
  - '2_months_ago: 16.0 routes'
  - '1_months_ago: 16.0 routes'
  - 'current_month: 16.0 routes'
  City of Torrance:
  - '2_months_ago: 12.0 routes'
  - '1_months_ago: 12.0 routes'
  - 'current_month: 12.0 routes'
  City of Turlock:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  City of Union City:
  - '2_months_ago: 5.0 routes'
  - '1_months_ago: 5.0 routes'
  - 'current_month: 5.0 routes'
  City of Vacaville:
  - '2_months_ago: 5.0 routes'
  - '1_months_ago: 5.0 routes'
  - 'current_month: 5.0 routes'
  City of Visalia:
  - '2_months_ago: 13.0 routes'
  - '1_months_ago: 13.0 routes'
  - 'current_month: 13.0 routes'
  City of West Hollywood:
  - '2_months_ago: 3.0 routes'
  - '1_months_ago: 3.0 routes'
  - 'current_month: 3.0 routes'
  Dumbarton Bridge Regional Operations Consortium:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  Eastern Contra Costa Transit Authority:
  - '2_months_ago: 15.0 routes'
  - '1_months_ago: 15.0 routes'
  - 'current_month: 15.0 routes'
  Eastern Sierra Transit Authority:
  - '2_months_ago: 14.0 routes'
  - '1_months_ago: 14.0 routes'
  - 'current_month: 14.0 routes'
  Golden Empire Transit District:
  - '2_months_ago: 15.0 routes'
  - '1_months_ago: 15.0 routes'
  - 'current_month: 15.0 routes'
  Golden Gate Bridge, Highway and Transportation District:
  - '2_months_ago: 16.0 routes'
  - '1_months_ago: 16.0 routes'
  - 'current_month: 16.0 routes'
  Humboldt Schedule:
  - '2_months_ago: 12.0 routes'
  - '1_months_ago: 12.0 routes'
  - 'current_month: 12.0 routes'
  Kern County:
  - '2_months_ago: 12.0 routes'
  - '1_months_ago: 12.0 routes'
  - 'current_month: 12.0 routes'
  Kings County Area Public Transit Agency:
  - '2_months_ago: 15.0 routes'
  - '1_months_ago: 15.0 routes'
  - 'current_month: 15.0 routes'
  Lake Transit Authority:
  - '2_months_ago: 9.0 routes'
  - '1_months_ago: 9.0 routes'
  - 'current_month: 9.0 routes'
  Livermore-Amador Valley Transit Authority:
  - '2_months_ago: 32.0 routes'
  - '1_months_ago: 32.0 routes'
  - 'current_month: 32.0 routes'
  Long Beach Transit:
  - '2_months_ago: 36.0 routes'
  - '1_months_ago: 36.0 routes'
  - 'current_month: 36.0 routes'
  Los Angeles County Metropolitan Transportation Authority:
  - '2_months_ago: 115.0 routes'
  - '1_months_ago: 115.0 routes'
  - 'current_month: 115.0 routes'
  Marin County Transit District:
  - '2_months_ago: 19.0 routes'
  - '1_months_ago: 19.0 routes'
  - 'current_month: 19.0 routes'
  Mountain Area Regional Transit Authority:
  - '2_months_ago: 14.0 routes'
  - '1_months_ago: 14.0 routes'
  - 'current_month: 14.0 routes'
  Mountain View Transportation Management Association:
  - '2_months_ago: 8.0 routes'
  - '1_months_ago: 8.0 routes'
  - 'current_month: 8.0 routes'
  Nevada County:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  North County Transit District:
  - '2_months_ago: 47.0 routes'
  - '1_months_ago: 47.0 routes'
  - 'current_month: 47.0 routes'
  OmniTrans:
  - '2_months_ago: 29.0 routes'
  - '1_months_ago: 29.0 routes'
  - 'current_month: 29.0 routes'
  Peninsula Corridor Joint Powers Board:
  - '2_months_ago: 4.0 routes'
  - '1_months_ago: 4.0 routes'
  - 'current_month: 4.0 routes'
  Presidio Trust:
  - '2_months_ago: 2.0 routes'
  - '1_months_ago: 2.0 routes'
  - 'current_month: 2.0 routes'
  Redding Schedule:
  - '2_months_ago: 12.0 routes'
  - '1_months_ago: 12.0 routes'
  - 'current_month: 12.0 routes'
  Redwood Coast Transit Authority:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  Riverside Transit Agency:
  - '2_months_ago: 35.0 routes'
  - '1_months_ago: 35.0 routes'
  - 'current_month: 35.0 routes'
  Sacramento Schedule:
  - '2_months_ago: 65.0 routes'
  - '1_months_ago: 65.0 routes'
  - 'current_month: 65.0 routes'
  San Francisco Bay Ferry and Oakland Alameda Water Shuttle Schedule:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  San Joaquin Regional Rail Commission:
  - '2_months_ago: 1.0 routes'
  - '1_months_ago: 1.0 routes'
  - 'current_month: 1.0 routes'
  San Luis Obispo Regional Transit Authority:
  - '2_months_ago: 15.0 routes'
  - '1_months_ago: 15.0 routes'
  - 'current_month: 15.0 routes'
  Santa Cruz Metropolitan Transit District:
  - '2_months_ago: 20.0 routes'
  - '1_months_ago: 20.0 routes'
  - 'current_month: 20.0 routes'
  Sonoma-Marin Area Rail Transit District:
  - '2_months_ago: 1.0 routes'
  - '1_months_ago: 1.0 routes'
  - 'current_month: 1.0 routes'
  Stanislaus Regional Transit Authority:
  - '2_months_ago: 27.0 routes'
  - '1_months_ago: 27.0 routes'
  - 'current_month: 27.0 routes'
  SunLine Transit Agency:
  - '2_months_ago: 19.0 routes'
  - '1_months_ago: 19.0 routes'
  - 'current_month: 19.0 routes'
  Tahoe Transportation District:
  - '2_months_ago: 5.0 routes'
  - '1_months_ago: 5.0 routes'
  - 'current_month: 5.0 routes'
  Tehama Schedule:
  - '2_months_ago: 9.0 routes'
  - '1_months_ago: 9.0 routes'
  - 'current_month: 9.0 routes'
  University of California, Berkeley:
  - '2_months_ago: 7.0 routes'
  - '1_months_ago: 7.0 routes'
  - 'current_month: 7.0 routes'
  University of California, Davis:
  - '2_months_ago: 19.0 routes'
  - '1_months_ago: 19.0 routes'
  - 'current_month: 19.0 routes'
  Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks) Schedule:
  - '2_months_ago: 61.0 routes'
  - '1_months_ago: 61.0 routes'
  - 'current_month: 61.0 routes'
  Victor Valley Transit Authority:
  - '2_months_ago: 66.0 routes'
  - '1_months_ago: 66.0 routes'
  - 'current_month: 66.0 routes'
  Western Contra Costa Transit Authority:
  - '2_months_ago: 11.0 routes'
  - '1_months_ago: 11.0 routes'
  - 'current_month: 11.0 routes'
