stop_segments:
    stage1: "vp_usable"
    stage2: "nearest_vp"
    stage3: "stop_arrivals"
    stage4: "speeds_stop_segments"
    stage5: "avg_speeds_stop_segments"
    stage6: "trip_speeds"
    stage7: "route_speeds"
    stage8: "avg_route_speeds_stop_segments"
    shape_rollup: "speeds_by_shape_peak_daytype"
    route_direction_rollup: "speeds_by_route_direction_peak_daytype"
    segments_file: "stop_segments"    
    segment_identifier_cols: ["shape_array_key", "stop_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
    pct_segment_minimum: 0.3
    max_speed: 80
road_segments:
    stage1: "vp_usable"
    stage2: "nearest_vp_roads"
    stage3: "stop_arrivals_roads"
    stage4: "speeds_road_segments"
    stage5: "avg_speeds_road_segments"
    segments_file: "road_segments"
    segment_identifier_cols: ["linearid", "mtfcc", "segment_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
