stop_segments:
    stage0: "vp"
    stage1: "vp_usable"
    stage2: "vp_stop_segment"
    stage3: "vp_pared_stops"
    stage4: "speeds_stop_segments"
    stage5: "avg_speeds_stop_segments"
    segments_file: "stop_segments"
    trip_grouping_cols: ["shape_array_key"]
    grouping_col: "shape_array_key"
    segment_identifier_cols: ["shape_array_key", "stop_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
    pct_segment_minimum: 0.3
road_segments:
    stage0: "vp"
    stage1: "vp_usable"
    stage2: "vp_road_segment"
    stage3: "vp_pared_roads"
    stage4: "speeds_road_segments"
    stage5: "avg_speeds_road_segments"
    segments_file: "road_segments"
    trip_grouping_cols: ["trip_instance_key"]
    grouping_col: None
    segment_identifier_cols: ["linearid", "mtfcc", "primary_direction", "segment_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
