stop_segments:
    stage1: "vp_usable"
    nearest_shape_segments: "nearest_vp_shape_segments"
    stage2: "nearest_vp"
    stage3: "stop_arrivals"
    stage4: "speeds_stop_segments"
    shape_stop_single_segment: "rollup_singleday/speeds_shape_stop_segments"
    route_dir_single_segment: "rollup_singleday/speeds_route_dir_segments"    
    trip_speeds_single_summary: "rollup_singleday/speeds_trip"
    route_dir_single_summary: "rollup_singleday/speeds_route_dir"
    route_dir_multi_segment: "rollup_multiday/speeds_route_dir_segments"
    route_dir_multi_summary: "rollup_multiday/speeds_route_dir"
    segments_file: "stop_segments"    
    segment_identifier_cols: ["shape_array_key", "stop_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
    max_speed: 80
rt_stop_times:
    stage1: "vp_usable"
    nearest_rt_stop_times: "nearest_vp_rt_stop_times"    
road_segments:
    stage1: "vp_usable"
    stage2: "nearest_vp_roads"
    stage3: "stop_arrivals_roads"
    stage4: "speeds_road_segments"
    stage5: "avg_speeds_road_segments"
    segments_file: "road_segments"
    segment_identifier_cols: ["linearid", "mtfcc", "segment_sequence"]
    timestamp_col: "location_timestamp_local"
    time_min_cutoff: 10
