RT_ARRIVAL_SEC = "rt_arrival_sec"
TRIP_INSTANCE_KEY = "trip_instance_key"
SCHEDULE_ARRIVAL_SEC = "schedule_arrival_sec"
STOP_SEQUENCE = "stop_sequence"
TRIP_ID = "trip_id"
STOP_ID = "stop_id"
SCHEDULE_GTFS_DATASET_KEY = "schedule_gtfs_dataset_key"

COLUMN_IDS = [
    RT_ARRIVAL_SEC,
    TRIP_INSTANCE_KEY,
    SCHEDULE_ARRIVAL_SEC,
    STOP_SEQUENCE,
    TRIP_ID,
    STOP_ID,
    SCHEDULE_GTFS_DATASET_KEY,
]

SCHEDULE_ARRIVAL_SEC_NAME = "scheduled_arrival_sec"
RT_ARRIVAL_SEC_NAME = "rt_arrival_sec"
STOP_SEQUENCE_NAME = "stop_sequence"
TRIP_INSTANCE_KEY_NAME = "trip_instance_key"
TRIP_ID_NAME = "trip_id"
STOP_ID_NAME = "stop_id"
SCHEDULE_GTFS_DATASET_KEY_NAME = "schedule_gtfs_dataset_key"

COLUMN_NAMES = [
    SCHEDULE_ARRIVAL_SEC_NAME,
    RT_ARRIVAL_SEC_NAME,
    STOP_SEQUENCE_NAME,
    TRIP_INSTANCE_KEY_NAME,
    TRIP_ID_NAME,
    STOP_ID_NAME,
    SCHEDULE_GTFS_DATASET_KEY_NAME
]

DEFAULT_COLUMN_MAP = {
    SCHEDULE_ARRIVAL_SEC: SCHEDULE_ARRIVAL_SEC_NAME,
    RT_ARRIVAL_SEC: RT_ARRIVAL_SEC_NAME,
    STOP_SEQUENCE: STOP_SEQUENCE_NAME,
    TRIP_INSTANCE_KEY: TRIP_INSTANCE_KEY_NAME,
    TRIP_ID: TRIP_ID_NAME,
    STOP_ID: STOP_ID_NAME,
    SCHEDULE_GTFS_DATASET_KEY: SCHEDULE_GTFS_DATASET_KEY_NAME
}
