generate_speedmaps_quickly:
	python update_vars_index.py
	python stage_run_portfolio.py
    # check console/logs/outputs, then manually deploy via stage_run_portfolio.deploy_portfolio()

clean_speedmap_progress:
	rm _rt_progress*
