setup_bus_service_utils:
	pip install -r requirements.txt
    
data_for_100_recs:
	python E1_get_buses_on_shn.py
	python E2_aggregated_route_stats.py
	#python E3_calculate_speeds_all_operators.py
	python E4_highway_segments_stats.py
    
