create_hqta_data:
	#pip install -r requirements.txt
	#python A1_rail_ferry_brt.py
	#python A2_combine.py
	#python B1_bus_corridors.py
	#python B2_combine_operator_corridors.py
	#python C1_prep_for_clipping.py
	#python C2_clip_bus_intersections.py
	python C4_create_bus_hqta_types.py
	python D1_assemble_hqta_points.py
	python D2_assemble_hqta_polygons.py

    

        
