#https://stackoverflow.com/questions/5484016/how-can-i-do-string-concatenation-or-string-replacement-in-yaml
gcs_paths:
  GCS: gs://calitp-analytics-data/data-analyses/ 
  COMPILED_CACHED_VIEWS: ${.GCS}rt_delay/compiled_cached_views/
  SEGMENT_GCS: ${.GCS}rt_segment_speeds/
  SCHED_GCS: ${.GCS}gtfs_schedule/
  RT_SCHED_GCS: ${.GCS}rt_vs_schedule/
  SHARED_GCS: ${.GCS}shared_data/

schedule_downloads:
  gcs_dir: ${gcs_paths.COMPILED_CACHED_VIEWS}
  trips: trips 
  shapes: routelines
  stops: stops
  stop_times: st

speeds_tables:
  gcs_dir: ${gcs_paths.SEGMENT_GCS}
  raw_vp_file: vp
  usable_vp_file: vp_usable 
  vp_condensed_line_file: condensed/vp_condensed
  vp_nearest_neighbor_file: condensed/vp_nearest_neighbor
  timestamp_col: "location_timestamp_local"
  time_min_cutoff: 10

schedule_tables:
  gcs_dir: ${gcs_paths.SCHED_GCS}
  gtfs_key_crosswalk: "crosswalk/gtfs_key_organization"
  route_identification_file: "standardized_route_ids"
  route_typologies_file: "nacto_typologies/route_typologies"
  monthly_scheduled_service_file: "scheduled_service_by_route"
  operator_scheduled_stats_file: "operator_profiles/operator_scheduled_stats"
  operator_route_file: "operator_profiles/operator_routes"

rt_vs_schedule_tables:
  dir: ${gcs_paths.RT_SCHED_GCS}
  stop_times_direction_file: "stop_times_direction"
  trip_metrics_file: "schedule_trip/schedule_trip_metrics"
  route_direction_metrics_file: "schedule_route_dir/schedule_route_direction_metrics"
  
shared_data:
  gcs_dir: ${gcs_paths.SHARED_GCS}
  road_segments_twomile: segmented_roads_twomile_2020
  road_segments_onekm: segmented_roads_onekm_2020