raw_vp_file: "vp"
usable_vp_file: "vp_usable"
vp_condensed_line_file: "condensed/vp_condensed"
vp_nearest_neighbor_file: "condensed/vp_nearest_neighbor"
timestamp_col: "location_timestamp_local"
time_min_cutoff: 10
stop_times_direction_file: "stop_times_direction"
trip_metrics_file: "schedule_trip/schedule_trip_metrics"
route_direction_metrics_file: "schedule_route_dir/schedule_route_direction_metrics"
route_identification_file: "standardized_route_ids"