name: Publish docs to gh-pages

on:
  pull_request:
    paths:
      - '.github/workflows/publish-site.yml'
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python packages
      run: |
        pip install -r requirements.txt

    # docs preview ----
    - name: Netlify docs preview
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        npm install -g netlify-cli
        jb build -W -n --keep-going ./docs
        netlify deploy --dir=docs/_build/html --alias=${GITHUB_REPOSITORY#*/}-${PR_NUMBER}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_APP_AUTH_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}

    - name: Add netlify link PR comment
      uses: actions/github-script@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const suffix = "--cal-itp-previews.netlify.app"
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Preview url: https://" + context.repo.repo + "-" + process.env.PR_NUMBER + suffix
          })
      env:
        PR_NUMBER: ${{ github.event.number }}
